# Numpy Basics

In [1]:
import numpy as np 

## ***Arrays***

In [2]:
#1-D Array
arr_1D = np.array([1,2,3,4])
arr_1D

array([1, 2, 3, 4])

In [3]:
#print dimensions of array
arr_1D.ndim

1

In [4]:
#2D array
arr_2D = np.array([
    [1,2,3],
    [2,3,4],
    [4,5,6]
])
arr_2D

array([[1, 2, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [5]:
arr_2D.ndim

2

In [6]:
# 3D array
arr_3D = np.array([
    [
        [1,2,3],
        [2,3,4],
        [4,5,6]
    ],
    [
        [1,2,3],
        [2,3,4],
        [4,5,6]
    ],
])
arr_3D

array([[[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]],

       [[1, 2, 3],
        [2, 3, 4],
        [4, 5, 6]]])

In [7]:
arr_3D.ndim

3

In [8]:
#shape returns the number of columns and number of rows or we can say Dimensions
print("Dimensions of 1D array : ", np.shape(arr_1D))
print("Dimensions of 2D array :", np.shape(arr_2D))
print("Dimensions of 3D array : ", np.shape(arr_3D))

Dimensions of 1D array :  (4,)
Dimensions of 2D array : (3, 3)
Dimensions of 3D array :  (2, 3, 3)


In [9]:
arr_2D[2,1] # row index = 2, col index = 1

5

### ***Slicing of arrays***

In [10]:
arr = np.arange(1, 20, 3) # create array from 1 to 20 with step size 3
arr

array([ 1,  4,  7, 10, 13, 16, 19])

In [11]:
n = arr[3:] #slicing arr from index 3 to end
n

array([10, 13, 16, 19])

In [12]:
a = arr_2D[:2, 1:] #slicing arr_2D from row 0 upto row 2 and col 1 upto end
a

array([[2, 3],
       [3, 4]])

### ***Reshape***

In [13]:
arr = np.array([1,2,3,4,5,6])
arr_reshaped = arr.reshape(2,3) # reshape in 2 rows and 3 cols
arr_reshaped

array([[1, 2, 3],
       [4, 5, 6]])

## ***Matrix Operations***

In [14]:
lst1 = np.arange(5,8)
lst2 = np.arange(10,13)
lst3 = np.arange(15,18)
lst4 = np.arange(20,23)
lst5 = np.arange(25,28)
lst6 = np.arange(30,33)

A = np.array([lst1, lst2, lst3])
B = np.array([lst4, lst5, lst6])

print(A , "\n\n")
print(B , "\n\n")
print(A.shape)
print(B.shape)

[[ 5  6  7]
 [10 11 12]
 [15 16 17]] 


[[20 21 22]
 [25 26 27]
 [30 31 32]] 


(3, 3)
(3, 3)


In [15]:
C = np.add(A,B)
C

array([[25, 27, 29],
       [35, 37, 39],
       [45, 47, 49]])

In [16]:
D = np.subtract(A,B)
D

array([[-15, -15, -15],
       [-15, -15, -15],
       [-15, -15, -15]])

### ***Transpose***

In [17]:
A_trans = A.T
A_trans

array([[ 5, 10, 15],
       [ 6, 11, 16],
       [ 7, 12, 17]])

In [18]:
B_trans = np.transpose(B)
B_trans

array([[20, 25, 30],
       [21, 26, 31],
       [22, 27, 32]])

### ***Multiplication***

In [19]:
mul = np.multiply(A, B) # point wise multiplication
mul

array([[100, 126, 154],
       [250, 286, 324],
       [450, 496, 544]])

In [20]:
mul1 = np.dot(A, B) # MAtrix multiplication
mul1

array([[ 460,  478,  496],
       [ 835,  868,  901],
       [1210, 1258, 1306]])

In [21]:
mul2 = A.dot(B) 
mul2

array([[ 460,  478,  496],
       [ 835,  868,  901],
       [1210, 1258, 1306]])

### ***Determinant***

present in linalg (linear algebra) module of numpy

In [22]:
det_A = np.linalg.det(A)
det_A

0.0

In [23]:
det_B = np.linalg.det(B)
det_B

7.105427357601044e-14

In [24]:
inv_B = np.linalg.inv(B)
inv_B #inverse of B

array([[-7.03687442e+13,  1.40737488e+14, -7.03687442e+13],
       [ 1.40737488e+14, -2.81474977e+14,  1.40737488e+14],
       [-7.03687442e+13,  1.40737488e+14, -7.03687442e+13]])

In [25]:
# inv_A = np.linalg.inv(A)
# here A is singular matrix i.e; det(A) = 0 , therefore inverse doesnot exist

In [26]:
# pseudo inverse 
pinv_A = np.linalg.pinv(A)
pinv_A

array([[-7.50000000e-01, -1.66666667e-01,  4.16666667e-01],
       [-3.33333333e-02,  1.70099629e-16,  3.33333333e-02],
       [ 6.83333333e-01,  1.66666667e-01, -3.50000000e-01]])

### ***Flatten***

Converts any dimension array to 1D array

In [27]:
flat_A = A.flatten()
flat_A

array([ 5,  6,  7, 10, 11, 12, 15, 16, 17])

## ***linspace***

In [44]:
x = np.linspace(-1, 1, 5)
y = np.linspace(-1, 1, 6)
X, Y = np.meshgrid(x, y)

print("X:\n", X)
print("Y:\n", Y)

X:
 [[-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]
 [-1.  -0.5  0.   0.5  1. ]]
Y:
 [[-1.  -1.  -1.  -1.  -1. ]
 [-0.6 -0.6 -0.6 -0.6 -0.6]
 [-0.2 -0.2 -0.2 -0.2 -0.2]
 [ 0.2  0.2  0.2  0.2  0.2]
 [ 0.6  0.6  0.6  0.6  0.6]
 [ 1.   1.   1.   1.   1. ]]


In [46]:
X.ravel()

array([-1. , -0.5,  0. ,  0.5,  1. , -1. , -0.5,  0. ,  0.5,  1. , -1. ,
       -0.5,  0. ,  0.5,  1. , -1. , -0.5,  0. ,  0.5,  1. , -1. , -0.5,
        0. ,  0.5,  1. , -1. , -0.5,  0. ,  0.5,  1. ])

In [47]:
Y.ravel()

array([-1. , -1. , -1. , -1. , -1. , -0.6, -0.6, -0.6, -0.6, -0.6, -0.2,
       -0.2, -0.2, -0.2, -0.2,  0.2,  0.2,  0.2,  0.2,  0.2,  0.6,  0.6,
        0.6,  0.6,  0.6,  1. ,  1. ,  1. ,  1. ,  1. ])

In [48]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])